# Generated by Django 5.0.1 on 2024-04-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_user_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
